import { addKeyword, EVENTS } from "@builderbot/bot";
import { generateTimer } from "../utils/generateTimer";
import { PatientsService } from "src/services/patients";
import { typing } from "src/utils/presence";
import { provider } from "src/provider";
import AIClass from "src/services/ai";
import { Patient } from "src/typings/patients";
import { GREETINGS_PROMPT } from "src/prompts/schedule.prompt";
import { MedicalService } from "src/services/medical-services";
import { Service } from "src/typings/medical-services";
import { MessageBrokerService } from "src/services/message-broker";
import { DATA_THERMS_QUEUE } from "src/queues";
