export enum INTENTIONS {
  TALK = "TALK",
  SCHEDULE_APPOINTMENT = "SCHEDULE_APPOINTMENT",
  PROMPT_INJECTION = "PROMPT_INJECTION",
  
  GENERAL_MEDICINE_APPOINTMENT = "GENERAL_MEDICINE_APPOINTMENT",
  DENTISTRY_FIRST_TIME_APPOINTMENT = "DENTISTRY_FIRST_TIME_APPOINTMENT",
  CLINICAL_LAB_APPOINTMENT = "CLINICAL_LAB_APPOINTMENT",

  PQRS = "PQRS",

  CHECK_SCHEDULED_APPOINTMENTS = "CHECK_SCHEDULED_APPOINTMENTS",
  CANCEL_SCHEDULED_APPOINTMENTS = "CANCEL_SCHEDULED_APPOINTMENTS",
  
  END_CHAT = "END_CHAT",
}
